apiVersion: v1
kind: Pod
metadata:
  name: pod-y-critical
  labels:
    app: critical-app
    xander.io/scenario: kubelet-disk-pressure
    xander.io/role: victim
spec:
  containers:
  - name: critical-app
    image: nginx:alpine
    readinessProbe:
      httpGet:
        path: /
        port: 80
      periodSeconds: 5
      timeoutSeconds: 2
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      # We intentionally omit limits and 'Guaranteed' QoS.
      # If DiskPressure is triggered, the kubelet will evict this pod!
